name: Python CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install local package
        run: pip install -e .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  docker:
     runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t hello_world_app_python .

      - name: Run container in background
        run: docker run -d -p 5000:5000 --name hello_app hello_world_app_python

      - name: Wait for app to be ready
        run: |
          for i in {1..15}; do
            if curl --silent http://localhost:5000/ > /dev/null; then
              echo "App is up!"
              exit 0
            fi
            echo "Waiting for app..."
            sleep 2
          done
          echo "App did not start in time" >&2
          docker logs hello_app
          exit 1

      - name: Run integration tests
        run: pytest tests/test_integration.py

      - name: Stop container
        run: docker stop hello_app